### PR TITLE
Add About Page

### PR DESCRIPTION
**Pull request by sarathms**
To be done

- [ ] Logo
- [ ] Button styling
- [ ] Font

And later we should get `ooni-components` in here along with `styled-components`

Screenshot_1571282670

### CODE REVIEW

**Comment by lorenzoPrimi** [comment]
are you sure to commit yarn.lock? I read that should be in gitignore

**Comment by sarathms** [comment]
For react native specifically? In general it is a good practice to keep it to be able to reproduce builds.

**Comment by lorenzoPrimi** [comment]
In every so answer they seems to put it in the gitignore
https://stackoverflow.com/questions/49099131/recommended-gitignore-for-react-native
I'll leave that to you

**Comment by hellais** [comment]
> In every so answer they seems to put it in the gitignore
> https://stackoverflow.com/questions/49099131/recommended-gitignore-for-react-native

As mentioned in the comment of the answer you linked to:

```
yarn.lock # include if you are using npm - don't use both npm and yarn
```

Since we use yarn in all our node projects (instead of npm) we should be committing the `yarn.lock` so that package versions are pinned.

**Comment by lorenzoPrimi** [comment]
I see, so I was doing something wrong when I used yarn or npm, we should stick to one.
In fact in the instructions I wrote
yarn add react-native (or npm install)
I'm gonna approve this PR

**Comment by sarathms** [comment]
Will remove the default version numbers I used for the screenshot and then merge this.

**Pull request merged**
